name: Xtream Playlist Extractor

on:
  workflow_dispatch:

jobs:
  extract-playlist:
    runs-on: ubuntu-latest
    steps:
      - name: Download Raw Playlist
        run: |
          curl -s -A "Mozilla/5.0 (Windows NT 10.0; Win64; x64)" "http://line.krishka.xyz:80/get.php?username=AdemSarikaya&password=16A525&type=m3u_plus" > playlist.m3u
      
      - name: Upload Playlist to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: xtream_raw_playlist
          path: playlist.m3u
